version: '3.9'
volumes:
  pgdata:
  static:
services:
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    depends_on:
      - webshop
    volumes:
      - static:/static
      - ./apps/webshop/media:/media/webshop
      - ./nginx_logs/apps:/nginx_logs
      - ./nginx_logs:/var/log/nginx/
    ports:
      - 80:80

  postgres:
    build:
      context: .
      dockerfile: docker/prod/postgres/Dockerfile
    restart: always
    environment:
      - POSTGRES_DB=webshop
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_data:/pg_data
    ports:
      - 5432:5432

  redis:
    build:
      context: .
      dockerfile: docker/prod/redis/Dockerfile
    ports:
      - 6379:6379

  webshop: &webshop
    build:
      context: .
      dockerfile: docker/prod/webshop/Dockerfile
    depends_on:
      - "postgres"
      - "redis"
    environment:
      - DJANGO_SETTINGS_MODULE=webshop.settings.prod
    volumes: 
      - ./apps/webshop:/apps/webshop
      - ./apps/webshop/media:/media/webshop
      - static:/static
    ports:
      - 8000:8000
      
    command: bash -c "python manage.py collectstatic --noinput
      && gunicorn -w 4 --access-logfile gunicorn.log webshop.wsgi -b 0.0.0.0:8000
      && celery -A webshop worker --loglevel=info -f celery.log -c 9"
