version: '3.9'
volumes:
  pgdata:
  static:
services:
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    depends_on:
      - calen_blog
      - webshop
      - zum_goldenen_panda
    volumes:
      - static:/static
      - ./apps/calen_blog/media:/media/calen_blog
      - ./apps/webshop/media:/media/webshop
      - ./apps/zum_goldenen_panda/media:/media/zum_goldenen_panda
      - ./nginx_logs/apps:/nginx_logs
      - ./nginx_logs:/var/log/nginx/
    ports:
      - 80:80

  postgres:
    build:
      context: .
      dockerfile: docker/prod/postgres/Dockerfile
    restart: always
    environment:
      - POSTGRES_DB=webshop
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_data:/pg_data
    ports:
      - 5432:5432

  redis:
    build:
      context: .
      dockerfile: docker/prod/redis/Dockerfile
    ports:
      - 6379:6379

  webshop: &webshop
    build:
      context: .
      dockerfile: docker/prod/webshop/Dockerfile
    depends_on:
      - "postgres"
      - "redis"
    environment:
      - DJANGO_SETTINGS_MODULE=webshop.settings.prod
    volumes: 
      - ./apps/webshop:/apps/webshop
      - ./apps/webshop/media:/media/webshop
      - static:/static
    ports:
      - 8000:8000
    command: bash -c "python manage.py collectstatic --noinput
      && gunicorn -w 4 --access-logfile gunicorn.log webshop.wsgi -b 0.0.0.0:8000"

  celery_worker_webshop:
    <<: *webshop
    command: celery -A webshop worker --loglevel=info -f celery.log -c 9
    ports: []

  calen_blog: &calen_blog
    build:
      context: .
      dockerfile: docker/prod/calen_blog/Dockerfile
    depends_on:
      - "postgres"
      - "redis"
    environment:
      - DJANGO_SETTINGS_MODULE=calen_blog.settings.prod
    volumes: 
      - ./apps/calen_blog:/apps/calen_blog
      - ./apps/calen_blog/media:/media/calen_blog
      - static:/static
    ports:
      - 8001:8001
    command: bash -c "python manage.py collectstatic --noinput
      && gunicorn -w 4 --access-logfile gunicorn.log calen_blog.wsgi -b 0.0.0.0:8001"

  zum_goldenen_panda: &zum_goldenen_panda
    build:
      context: .
      dockerfile: docker/prod/zum_goldenen_panda/Dockerfile
    depends_on:
      - "postgres"
      - "redis"
    environment:
      - DJANGO_SETTINGS_MODULE=zum_goldenen_panda.settings.prod
    volumes: 
      - ./apps/zum_goldenen_panda:/apps/zum_goldenen_panda
      - ./apps/zum_goldenen_panda/media:/media/zum_goldenen_panda
      - static:/static
    ports:
      - 8002:8002
    command: bash -c "python manage.py collectstatic --noinput
      && gunicorn -w 4 --access-logfile gunicorn.log zum_goldenen_panda.wsgi -b 0.0.0.0:8002"
